### PR TITLE
Use ruamel.yaml to match conda; improve tests

### PR DESCRIPTION
**Pull request by dholth**
### Description

Use same yaml library as conda.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Review by jezdez — COMMENTED** [review]
Are there concerns around differences in parsing or supported YAML version between the two libraries?

**Comment by dholth** [comment]
> Are there concerns around differences in parsing or supported YAML version between the two libraries?

ruamel.yaml in pure Python mode parses YAML 1.2 which e.g. has more predictable boolean parsing (fewer aliases for booleans).

**Review by jezdez — APPROVED** [review]

**Comment by jezdez** [comment]
This will need changes to the feedstock and given the rather big change to this, I'm wondering if we should do some trials to test the differences in runtime and output?

**Comment by dholth** [comment]
We could possibly run it against defaults for a while, or all the packages included in an Anaconda3 distribution and compare the generated cache databases. Or we could dump all the meta.yaml from a selection of packages, parse them with both and compare the json just to compare the parsers outside of conda-index.

The runtime of conda-index is almost certainly dominated by the decompression algorithms, then we convert yaml to json, store the json in sqlite and never speak of it again.

**Pull request merged**
