### PR TITLE
Fix a few errors in the first-party recipe (following changes from conda-forge)

### PR DESCRIPTION
**Pull request by dholth**
### Description

This pull request makes the recipe look like https://github.com/conda-forge/conda-index-feedstock/blob/main/recipe/meta.yaml

We removed the conda-index script (promoting python -m conda_index) to avoid conflict with conda-build's conda index. We removed some comments and setuptools-style extra markers that are not supported in conda recipes.

(Hopefully the "conda index" conflict will be resolved in a more satisfying way in a future conda-build release)

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by dholth** [comment]
@jharlow-intel this is the flawed upstream feedstock.

Do you have any user feedback for the conda-index package?

**Comment by jharlow-intel** [comment]
> @jharlow-intel this is the flawed upstream feedstock.
> 
> Do you have any user feedback for the conda-index package?

I'm pretty new to it but so far I think it works well as-is! Will let you know if I have better feedback to give in the future

**Comment by dholth** [comment]
Thanks @jharlow-intel sounds like you have used new conda index more than the one included with conda-build and have no feedback on the comparison

**Comment by jezdez** [comment]
@dholth I'm not sure I follow what this is about, could you elaborate in the PR description please?

**Review by jezdez — APPROVED** [review]

**Pull request merged**
